// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    QR_SCENE: 'QR_SCENE',
    QR_LIMIT_SCENE: 'QR_LIMIT_SCENE',
    QR_LIMIT_STR_SCENE: 'QR_LIMIT_STR_SCENE'
  };

}).call(this);
