// Generated by CoffeeScript 1.8.0

/*
 * 微信自定义菜单的接口工具类
 */

(function() {
  var RequestUrls, assert, createMenus, debuglog, deleteMenus, loadMenus, request;

  debuglog = require("debug")("weixin_tools");

  assert = require("assert");

  request = require('request');

  RequestUrls = require("../enums/request_urls");

  loadMenus = function(access_token, callback) {
    var options, url;
    url = "" + RequestUrls.GET_MENUS_URL + "?access_token=" + access_token;
    options = {
      url: url,
      json: true,
      method: "GET"
    };
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      if ((body.errcode != null) && parseInt(body.errcode) !== 0) {
        return callback(new Error("errCode" + body.errcode + " " + body.errmsg));
      }
      return callback(null, body);
    });
  };

  deleteMenus = function(access_token, callback) {
    var options, url;
    url = "" + RequestUrls.DELETE_MENUS_URL + "?access_token=" + access_token;
    options = {
      url: url,
      json: true,
      method: "GET"
    };
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      if ((body.errcode != null) && parseInt(body.errcode) !== 0) {
        return callback(new Error("errCode" + body.errcode + " " + body.errmsg));
      }
      return callback(null, body);
    });
  };

  createMenus = function(access_token, menus, callback) {
    var options, url;
    url = "" + RequestUrls.POST_MENUS_URL + "?access_token=" + access_token;
    options = {
      url: url,
      json: true,
      method: "POST",
      body: menus
    };
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      if ((body.errcode != null) && parseInt(body.errcode) !== 0) {
        return callback(new Error("errCode" + body.errcode + " " + body.errmsg));
      }
      return callback(null, body);
    });
  };

  module.exports = {
    loadMenus: loadMenus,
    deleteMenus: deleteMenus,
    createMenus: createMenus
  };

}).call(this);
