// Generated by CoffeeScript 1.8.0

/*
 * 微信发送消息的接口
 */

(function() {
  var RequestUrls, assert, debuglog, request, sendTemplateMessage, _;

  debuglog = require("debug")("weixin_tools");

  _ = require('underscore');

  assert = require("assert");

  request = require('request');

  RequestUrls = require("../enums/request_urls");


  /*
   *发送模板消息
   *params
    msg =
        "touser":"o-5Zdt8pmmpmYqXbTbDUpXwx_kOk"
        "template_id":"Cx7lfTxetVWVKf77h8DRyEj93XfcazYt3faMl9Hhwl8"
        "url":"http://weixin.gamagame.cn"
        "topcolor":"#FF0000"
        "data":
           "first":
             "value":"您预约报名参加的活动，将要开始了"
             "color":"#173177"
           "keynote1":
             "value":"皇上快点群妃乱斗"
             "color":"#173177"
           "keynote2":
             "value":"今天10:00"
             "color":"#173177"
           "remark":
             "value":"欢迎进入游戏"
             "color":"#173177"
    access_token: access_token
   *return '{"errcode":40003,"errmsg":"invalid openid"}' or '{"errcode":0,"errmsg":"ok","msgid":204924419}'
   */

  sendTemplateMessage = function(msg, access_token, callback) {
    var options, url;
    assert(_.isFunction(callback), "missing callback");
    console.dir(msg);
    if (!((msg != null) && !_.isEmpty(msg))) {
      return callback(new Error("msg is empty"));
    }
    url = "" + RequestUrls.SEND_TEMPLATE_MESSAGE_URL + "?access_token=" + access_token;
    options = {
      url: url,
      json: true,
      method: "POST",
      body: JSON.stringify(msg)
    };
    request(options, (function(_this) {
      return function(err, res, body) {
        if (err != null) {
          return callback(err);
        }
        if (body == null) {
          return callback(new Error("invalid body"));
        }
        if (!(body.errcode === 0 && body.errmsg === 'ok')) {
          return callback(new Error("" + body.errcode + ":" + body.errmsg));
        }
        callback(null, body);
      };
    })(this));
  };

  module.exports = {
    sendTemplateMessage: sendTemplateMessage
  };

}).call(this);
