// Generated by CoffeeScript 1.8.0

/*
 * 微信的oauth 登录方式实现工具
 */

(function() {
  var RequestUrls, assert, createQrcode, debuglog, querystring, request, _;

  debuglog = require("debug")("utils::oauth");

  assert = require("assert");

  request = require('request');

  _ = require('underscore');

  querystring = require("querystring");

  RequestUrls = require("../enums/request_urls");

  createQrcode = function(access_token, action_info, expire_seconds, action_name, callback) {
    var data, options, url;
    url = "" + RequestUrls.QRCODE_CREATE_URL + "?access_token=" + access_token;
    data = {
      expire_seconds: expire_seconds,
      action_name: action_name,
      action_info: action_info
    };
    options = {
      url: url,
      json: true,
      method: "POST",
      body: data
    };
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      if ((body.errcode != null) && parseInt(body.errcode) !== 0) {
        return callback(new Error("errCode" + body.errcode + " " + body.errmsg));
      }
      return callback(null, body);
    });
  };

  module.exports = {
    createQrcode: createQrcode
  };

}).call(this);
