// Generated by CoffeeScript 1.8.0

/*
 * 微信的签名算法工具
 */

(function() {
  var checkSignature, crypto, debuglog, helps, makeSignature, request, _;

  debuglog = require("debug")("utils::signature");

  crypto = require('crypto');

  request = require('request');

  _ = require('underscore');

  helps = require("../utils/helps");

  makeSignature = function(args) {
    var digest, str;
    str = helps.raw(args);
    digest = crypto.createHash("sha1").update(str).digest("hex");
    return digest;
  };

  checkSignature = function(signature, args) {
    var sign;
    sign = makeSignature(args);
    return sign === signature;
  };

  module.exports = {
    makeSignature: makeSignature,
    checkSignature: checkSignature
  };

}).call(this);
