// Generated by CoffeeScript 1.8.0

/*
 * 系统配置文件
 */

(function() {
  module.exports = {
    development: {
      appid: "wxe91769cfb4209cc5",
      secret: "4d11b075fa41d1c833a276db102d3366",
      payOptions: {
        mchId: '1230578602',
        partnerKey: 'sgf98R7589iHI9e47568Qs028767UWsw',
        notifyUrl: 'http://weixin.qq.cn'
      },
      menus: {
        "button": [
          {
            "type": "click",
            "name": "游戏社区",
            "key": "V1001_TODAY_MUSIC",
            "sub_button": []
          }, {
            "type": "view",
            "name": "进入游戏",
            "url": "http://www.weixin.com",
            "sub_button": []
          }, {
            "name": "菜单",
            "sub_button": [
              {
                "type": "view",
                "name": "最新活动",
                "url": "http://www.weixin.com"
              }, {
                "type": "view",
                "name": "搜索",
                "url": "http://www.soso.com"
              }
            ]
          }
        ]
      }
    }
  };

}).call(this);
