// Generated by CoffeeScript 1.8.0

/*
 * 公共的帮助类(这里的接口只提供本项目自身调用， 不提供对外调用)
 */

(function() {
  var debuglog, raw, _;

  debuglog = require("debug")("utils::helps");

  _ = require('underscore');

  raw = function(args) {
    var k, keys, newArgs, str, v;
    keys = _.keys(args);
    keys = keys.sort();
    newArgs = {};
    keys.forEach(function(key) {
      return newArgs[key.toLowerCase()] = args[key];
    });
    str = "";
    for (k in newArgs) {
      v = newArgs[k];
      str += "&" + k + "=" + v;
    }
    return str.substr(1);
  };

  module.exports = {
    raw: raw
  };

}).call(this);
