// Generated by CoffeeScript 1.8.0

/*
 * 公共的帮助类(这里的接口只提供本项目自身调用， 不提供对外调用)
 */

(function() {
  var debuglog, json2xml, raw, xml2json, xmlParser, _;

  debuglog = require("debug")("utils::helps");

  _ = require('underscore');

  xmlParser = require('xml2json');

  raw = function(args) {
    var k, keys, newArgs, str, v;
    keys = _.keys(args);
    keys = keys.sort();
    newArgs = {};
    keys.forEach(function(key) {
      return newArgs[key.toLowerCase()] = args[key];
    });
    str = "";
    for (k in newArgs) {
      v = newArgs[k];
      str += "&" + k + "=" + v;
    }
    return str.substr(1);
  };

  xml2json = function(xml) {
    var err, str;
    str = xmlParser.toJson(xml);
    if (!str) {
      return;
    }
    try {
      console.log(str);
      console.log(xmlParser.toXml(str));
      return JSON.parse(str).xml;
    } catch (_error) {
      err = _error;
      debuglog("[ERROR] error: " + err);
    }
    return null;
  };

  json2xml = function(json) {
    return xmlParser.toXml(json);
  };

  module.exports = {
    raw: raw,
    xml2json: xml2json,
    json2xml: json2xml
  };

}).call(this);
