// Generated by CoffeeScript 1.8.0

/*
 * 公共的帮助类(这里的接口只提供本项目自身调用， 不提供对外调用)
 */

(function() {
  var debuglog, json2xml, querystring, rank, rankAndEncode, raw, xml2js, xml2json, _;

  debuglog = require("debug")("utils::helps");

  _ = require('underscore');

  xml2js = require('xml2js');

  querystring = require("querystring");

  rank = function(args) {
    var keys, newArgs;
    keys = _.keys(args);
    keys = keys.sort();
    newArgs = {};
    keys.forEach(function(key) {
      return newArgs[key] = args[key];
    });
    return newArgs;
  };

  rankAndEncode = function(args) {
    var keys, newArgs;
    keys = _.keys(args);
    keys = keys.sort();
    newArgs = {};
    keys.forEach(function(key) {
      return newArgs[key] = args[key];
    });
    return newArgs;
  };

  raw = function(args) {
    var k, keys, newArgs, str, v;
    keys = _.keys(args);
    keys = keys.sort();
    newArgs = {};
    keys.forEach(function(key) {
      return newArgs[key] = args[key];
    });
    str = "";
    for (k in newArgs) {
      v = newArgs[k];
      str += "&" + k + "=" + v;
    }
    str = str.substr(1);
    return str;
  };

  xml2json = function(xml, callback) {
    return xml2js.parseString(xml, {
      trim: true,
      explicitArray: false
    }, function(err, json) {
      var data;
      if (err != null) {
        return callback(err);
      }
      data = json != null ? json.xml : {};
      return callback(null, data);
    });
  };

  json2xml = function(obj) {
    var builder, xml;
    builder = new xml2js.Builder();
    xml = builder.buildObject({
      xml: obj
    });
    return xml;
  };

  module.exports = {
    rank: rank,
    rankAndEncode: rankAndEncode,
    raw: raw,
    xml2json: xml2json,
    json2xml: json2xml
  };

}).call(this);
