// Generated by CoffeeScript 1.8.0

/*
 * 微信的签名算法工具
 */

(function() {
  var checkSignature, crypto, debuglog, makeSignature, request, _, _raw;

  debuglog = require("debug")("utils::signature");

  crypto = require('crypto');

  request = require('request');

  _ = require('underscore');

  _raw = function(args) {
    var k, keys, newArgs, str, v;
    keys = _.keys(args);
    keys = keys.sort();
    newArgs = {};
    keys.forEach(function(key) {
      return newArgs[key.toLowerCase()] = args[key];
    });
    str = "";
    for (k in newArgs) {
      v = newArgs[k];
      str += "&" + k + "=" + v;
    }
    return str.substr(1);
  };

  makeSignature = function(url, jsapi_ticket, noncestr, timestamp) {
    var args, digest, str;
    args = {
      url: url,
      jsapi_ticket: jsapi_ticket,
      noncestr: noncestr,
      timestamp: timestamp
    };
    str = _raw(args);
    digest = crypto.createHash("sha1").update(str).digest("hex");
    return digest;
  };

  checkSignature = function(signature, url, jsapi_ticket, noncestr, timestamp) {
    var sign;
    sign = makeSignature(url, jsapi_ticket, noncestr, timestamp);
    return sign === signature;
  };

  module.exports = {
    makeSignature: makeSignature,
    checkSignature: checkSignature
  };

}).call(this);
