// Generated by CoffeeScript 1.8.0
(function() {
  var helps, json_test, raw_test, should, xml_test, _;

  should = require("should");

  _ = require('underscore');

  helps = require("../utils/helps");

  raw_test = {
    sign: "asdfasdfaiwoehklnafhan;lajsdfajfasfaf",
    name: "小Q",
    age: 12
  };

  xml_test = "<xml>\n  <appid>wx2421b1c4370ec43b</appid>\n  <appid2><![CDATA[wx2421b1c4370ec43b]]></appid2>\n  <attach>支付测试</attach>\n  <body>JSAPI支付测试</body>\n  <mch_id>10000100</mch_id>\n  <nonce_str>1add1a30ac87aa2db72f57a2375d8fec</nonce_str>\n  <notify_url>http://wxpay.weixin.qq.com/pub_v2/pay/notify.v2.php</notify_url>\n  <openid>oUpF8uMuAJO_M2pxb1Q9zNjWeS6o</openid>\n  <out_trade_no>1415659990</out_trade_no>\n  <spbill_create_ip>14.23.150.211</spbill_create_ip>\n  <total_fee>1</total_fee>\n  <trade_type>JSAPI</trade_type>\n  <sign>0CB01533B8C1EF103065174F50BCA001</sign>\n</xml>";

  json_test = {
    "xml": {
      "appid": 'wx2421b1c4370ec43b',
      "appid2": 'wx2421b1c4370ec43b',
      "attach": '支付测试',
      "body": 'JSAPI支付测试',
      "mch_id": 10000100,
      "nonce_str": '1add1a30ac87aa2db72f57a2375d8fec',
      "notify_url": 'http://wxpay.weixin.qq.com/pub_v2/pay/notify.v2.php',
      "openid": 'oUpF8uMuAJO_M2pxb1Q9zNjWeS6o',
      "out_trade_no": 1415659990,
      "spbill_create_ip": '14.23.150.211',
      "total_fee": 1,
      "trade_type": 'JSAPI',
      "sign": '0CB01533B8C1EF103065174F50BCA001'
    }
  };

  describe("test utils helps", function() {
    before(function() {});
    return describe("test", function() {
      it("raw", function(done) {
        console.log(helps.raw(raw_test));
        return done();
      });
      it("xml 2 json", function(done) {
        console.dir(helps.xml2json(xml_test));
        return done();
      });
      return it("json 2 xml", function(done) {
        console.log(helps.json2xml(json_test));
        return done();
      });
    });
  });

}).call(this);
