// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinTools, config, env, jsapi_ticket, menus, noncestr, options, p, should, signArgs, signature, timestamp, token, url, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  menus = config.menus;

  noncestr = "Wm3WZYTPz0wzccnW";

  jsapi_ticket = "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg";

  timestamp = "1414587457";

  url = "http://mp.weixin.qq.com?params=value";

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signArgs = {
    noncestr: "Wm3WZYTPz0wzccnW",
    jsapi_ticket: "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg",
    timestamp: "1414587457",
    url: "http://mp.weixin.qq.com?params=value"
  };

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions,
    jsApiList: config.jsApiList
  };

  wxt = new WeixinTools(options);

  token = null;

  describe("test weixin_tools", function() {
    before(function() {});
    describe("token", function() {
      it("should get access_token", function(done) {
        return wxt.loadAccessToken(function(err, data) {
          if (err != null) {
            console.dir(err);
          }
          token = data;
          console.dir(token);
          return done();
        });
      });
      return it("should get jsapi_ticket", function(done) {
        if (token == null) {
          return done();
        }
        return wxt.loadJsapiTicket(token.access_token, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
    });
    return describe("material", function() {
      it("load material count", function(done) {
        return wxt.loadMaterialCount(token.access_token, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
      it("load material list", function(done) {
        return wxt.loadMaterialList(token.access_token, "voice", 0, 20, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
      return it("get material by id", function(done) {
        return wxt.getMaterialById(token.access_token, '', function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
    });
  });

}).call(this);
