// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinTools, config, env, jsapi_ticket, menus, noncestr, options, p, should, signArgs, signature, timestamp, token, url, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  menus = config.menus;

  noncestr = "Wm3WZYTPz0wzccnW";

  jsapi_ticket = "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg";

  timestamp = "1414587457";

  url = "http://mp.weixin.qq.com?params=value";

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signArgs = {
    noncestr: "Wm3WZYTPz0wzccnW",
    jsapi_ticket: "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg",
    timestamp: "1414587457",
    url: "http://mp.weixin.qq.com?params=value"
  };

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions,
    jsApiList: config.jsApiList
  };

  wxt = new WeixinTools(options);

  token = null;

  describe("test weixin_tools", function() {
    before(function() {});
    return describe("material", function() {
      token = {
        access_token: "9SXQSIztoloEJef_dwq9M4pJyP7oFLzfEHjflADLf2GlBKSvfyCxRX5B5pNlUT3902mNC9AUwTDCKelaCBOFQ_N-Rnofl7sOZaE_Skxz-hU",
        ticket: "9SXQSIztoloEJef_dwq9M4pJyP7oFLzfEHjflADLf2GlBKSvfyCxRX5B5pNlUT3902mNC9AUwTDCKelaCBOFQ_N-Rnofl7sOZaE_Skxz-hU"
      };
      return it("add voice material", function(done) {
        var filename;
        filename = "/Users/user/Downloads/2dLwJrA.mp3";
        return wxt.uploadMedia(token.access_token, 'voice', filename, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
    });
  });

}).call(this);
