// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinTools, config, env, jsapi_ticket, menus, noncestr, options, p, should, signature, subscribeXML, timestamp, token, url, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  menus = config.menus;

  noncestr = "Wm3WZYTPz0wzccnW";

  jsapi_ticket = "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg";

  timestamp = "1414587457";

  url = "http://mp.weixin.qq.com?params=value";

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions,
    jsApiList: config.jsApiList,
    originalID: config.originalID
  };

  wxt = new WeixinTools(options);

  token = null;

  subscribeXML = "<xml>\n  <ToUserName>asdfasfa<ToUserName>\n  <FromUserName>dsafasfasf</FromUserName>\n  <CreateTime>123456789</CreateTime>\n  <MsgType><![CDATA[event]]></MsgType>\n  <Event><![CDATA[subscribe]]></Event>\n</xml>";

  describe("test weixin_tools", function() {
    before(function() {});
    return describe("message", function() {
      token = {
        access_token: "nfbIHl9p_TyQFJ6KQvF3YTrjIG1QjB14KhoRlmQ8fjCwfHHjDV7uJWL7KB3PZR4dW95QBupypwNP_tCGuuX8oEdxVNyiuxd-whpJZ2hN_dE",
        ticket: "sM4AOVdWfPE4DxkXGEs8VFj5UEhJXZMbuiU3wOuFKqHuT5pm3O9Y1kLceFR_XIIdtcVN9YNpVpDvUBUq7nSLkA"
      };
      return it("send auto message", function(done) {
        subscribeXML = "<xml><URL><![CDATA[http://mintr-dev.gamagama.cn/weixin/wechat]]></URL><ToUserName><![CDATA[wxe143a2b06d92c16b]]></ToUserName><FromUserName><![CDATA[o-5Zdt8pmmpmYqXbTbDUpXwx_kOk]]></FromUserName><CreateTime>1427706395</CreateTime><MsgType><![CDATA[text]]></MsgType><Content><![CDATA[asdfasf]]></Content><MsgId>1</MsgId></xml>";
        return wxt.receiveMessage(subscribeXML, function(err, data) {
          var result;
          if (err != null) {
            console.error(err);
          }
          console.dir(data);
          result = wxt.autoReplyMessage(data.FromUserName, data.MsgType, data.Content || data.MediaId);
          console.log(result);
          return done();
        });
      });
    });
  });

}).call(this);
