// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinTools, config, env, jsapi_ticket, menus, noncestr, options, p, should, signature, subscribeXML, timestamp, token, url, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  menus = config.menus;

  noncestr = "Wm3WZYTPz0wzccnW";

  jsapi_ticket = "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg";

  timestamp = "1414587457";

  url = "http://mp.weixin.qq.com?params=value";

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions,
    jsApiList: config.jsApiList,
    originalID: config.originalID
  };

  wxt = new WeixinTools(options);

  token = null;

  subscribeXML = "<xml>\n  <ToUserName>asdfasfa<ToUserName>\n  <FromUserName>dsafasfasf</FromUserName>\n  <CreateTime>123456789</CreateTime>\n  <MsgType><![CDATA[event]]></MsgType>\n  <Event><![CDATA[subscribe]]></Event>\n</xml>";

  describe("test weixin_tools", function() {
    return before(function() {});
  });

}).call(this);
