// Generated by CoffeeScript 1.8.0
(function() {
  var PROMOTION_CHECK_NAME, WeixinTools, caFile, certFile, config, env, fs, keyFile, menus, obj, options, p, path, pfxFile, should, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  fs = require('fs');

  path = require('path');

  pfxFile = path.resolve(__dirname, '../../ssl/apiclient_cert.p12');

  certFile = path.resolve(__dirname, '../../ssl/apiclient_cert.pem');

  keyFile = path.resolve(__dirname, '../../ssl/apiclient_key.pem');

  caFile = path.resolve(__dirname, '../../ssl/rootca.pem');

  menus = config.menus;

  WeixinTools = require("../weixin_tools");

  console.dir(config);

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions,
    jsApiList: config.jsApiList,
    sslCert: fs.readFileSync(certFile),
    sslKey: fs.readFileSync(keyFile),
    sslCa: fs.readFileSync(caFile),
    sslPfx: fs.readFileSync(pfxFile)
  };

  wxt = new WeixinTools(options);

  console.dir(wxt);

  console.dir(wxt.PROMOTION_CHECK_NAME);

  PROMOTION_CHECK_NAME = wxt.PROMOTION_CHECK_NAME;

  obj = {
    partner_trade_no: '10000098201411111234567890',
    openid: 'oJB0rwqcoxDeM1w3TDw_CTxipH5Q',
    check_name: PROMOTION_CHECK_NAME.NO_CHECK,
    amount: 100,
    desc: '测试->接口测试->企业付款功能接口测试',
    spbill_create_ip: '127.0.0.1'
  };

  describe("test promotion", function() {
    before(function() {});
    return describe("transfers", function() {
      return it("should transfers", function(done) {
        return wxt.promotion(obj, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.log(JSON.stringify(data));
          return done();
        });
      });
    });
  });

}).call(this);
