// Generated by CoffeeScript 1.8.0
(function() {
  var QRCODE_ACTION_NAME, WeixinTools, action_info, config, env, expire_seconds, menus, options, p, should, token, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  menus = config.menus;

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions,
    jsApiList: config.jsApiList
  };

  wxt = new WeixinTools(options);

  console.dir(wxt);

  console.dir(wxt.QRCODE_ACTION_NAME);

  QRCODE_ACTION_NAME = wxt.QRCODE_ACTION_NAME;

  expire_seconds = 2592000;

  action_info = {
    scene: {
      scene_str: "account_at"
    }
  };

  token = null;

  describe("test weixin_tools", function() {
    before(function() {});
    describe("token", function() {
      it("should get access_token", function(done) {
        return wxt.loadAccessToken(function(err, data) {
          if (err != null) {
            console.dir(err);
          }
          token = data;
          console.dir(token);
          return done();
        });
      });
      return it("should get jsapi_ticket", function(done) {
        if (token == null) {
          return done();
        }
        return wxt.loadJsapiTicket(token.access_token, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
    });
    return describe("qrcode", function() {
      it("should create qrcode ", function(done) {
        if (token == null) {
          return done();
        }
        return wxt.createQrcode(token.access_token, action_info, expire_seconds, QRCODE_ACTION_NAME.QR_SCENE, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.log(JSON.stringify(data));
          return done();
        });
      });
      it("should create QR_LIMIT_SCENE qrcode", function(done) {
        if (token == null) {
          return done();
        }
        return wxt.createQrcode(token.access_token, action_info, expire_seconds, QRCODE_ACTION_NAME.QR_LIMIT_SCENE, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.log(JSON.stringify(data));
          return done();
        });
      });
      return it("should create QR_LIMIT_STR_SCENE qrcode", function(done) {
        if (token == null) {
          return done();
        }
        return wxt.createQrcode(token.access_token, action_info, expire_seconds, QRCODE_ACTION_NAME.QR_LIMIT_STR_SCENE, function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.log(JSON.stringify(data));
          return done();
        });
      });
    });
  });

}).call(this);
