// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinTools, config, env, jsapi_ticket, menus, noncestr, options, p, should, signArgs, signature, timestamp, token, url, wxt, _;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  _ = require('underscore');

  config = require('../config/config')[env];

  menus = config.menus;

  noncestr = "Wm3WZYTPz0wzccnW";

  jsapi_ticket = "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg";

  timestamp = "1414587457";

  url = "http://mp.weixin.qq.com?params=value";

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signArgs = {
    noncestr: "Wm3WZYTPz0wzccnW",
    jsapi_ticket: "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg",
    timestamp: "1414587457",
    url: "http://mp.weixin.qq.com?params=value"
  };

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret,
    payOptions: config.payOptions
  };

  wxt = new WeixinTools(options);

  console.dir(wxt);

  token = null;

  describe("test weixin_tools", function() {
    before(function() {});
    describe("oauth", function() {
      return it("generateAuthorizeURL", function(done) {
        var url1, url2, url3;
        url1 = wxt.generateAuthorizeURL("http://www.baidu.com");
        console.log(url1);
        url2 = wxt.generateAuthorizeURL("http://www.baidu.com", "haha");
        console.log(url2);
        url3 = wxt.generateAuthorizeURL("http://www.baidu.com", "haha", "snsapi_userinfo");
        console.log(url3);
        return done();
      });
    });
    return describe("pay", function() {
      it("makePaySignature", function(done) {
        var args, sign;
        args = {
          appid: 'wxd930ea5d5a258f4f',
          device_info: 1000,
          body: "test",
          nonce_str: 'ibuaiVcKdpRxkhJA',
          mch_id: wxt.payOptions.mchId
        };
        sign = wxt.makePaySignature(args);
        console.log("pay sign : " + sign);
        return done();
      });
      return it("getBrandWCPayRequestParams", function(done) {
        var order;
        order = {
          body: '吮指原味鸡',
          out_trade_no: 'kfc003',
          total_fee: 1,
          spbill_create_ip: "8.8.8.8",
          openid: "o-5Zdt8pmmpmYqXbTbDUpXwx_kOk",
          trade_type: 'JSAPI'
        };
        return wxt.getBrandWCPayRequestParams(order, function(err, body) {
          console.error("ERROR: " + err);
          console.dir(body);
          return done();
        });
      });
    });
  });

}).call(this);
