// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinTools, config, env, jsapi_ticket, menus, noncestr, options, p, should, signature, timestamp, token, url, wxt;

  should = require("should");

  p = require("commander");

  env = p.environment || 'development';

  config = require('../config/config')[env];

  menus = config.menus;

  noncestr = "Wm3WZYTPz0wzccnW";

  jsapi_ticket = "sM4AOVdWfPE4DxkXGEs8VMCPGGVi4C3VM0P37wVUCFvkVAy_90u5h9nbSlYy3-Sl-HhTdfl2fzFy1AOcHKP7qg";

  timestamp = "1414587457";

  url = "http://mp.weixin.qq.com?params=value";

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  signature = '0f9de62fce790f9a083d5c99e95740ceb90c27ed';

  WeixinTools = require("../weixin_tools");

  options = {
    appid: config.appid,
    secret: config.secret
  };

  wxt = new WeixinTools(options.appid, options.secret);

  token = null;

  describe("test weixin_util", function() {
    before(function() {});
    describe("signature", function() {
      it("makeSignature", function(done) {
        var sign;
        sign = wxt.makeSignature(url, jsapi_ticket, noncestr, timestamp);
        console.log("sign: " + sign);
        return done();
      });
      it("checkSignature", function(done) {
        var check;
        check = wxt.checkSignature(signature, url, jsapi_ticket, noncestr, timestamp);
        console.log("check: " + check);
        return done();
      });
      return it("generateConfig", function(done) {
        config = wxt.generateConfig(url, jsapi_ticket);
        console.dir(config);
        return done();
      });
    });
    return describe("oauth", function() {
      it("generateAuthorizeURL", function(done) {
        var url1, url2, url3;
        url1 = wxt.generateAuthorizeURL("http://www.baidu.com");
        console.log(url1);
        url2 = wxt.generateAuthorizeURL("http://www.baidu.com", "haha");
        console.log(url2);
        url3 = wxt.generateAuthorizeURL("http://www.baidu.com", "haha", "snsapi_userinfo");
        console.log(url3);
        return done();
      });
      return it("loadAuthorzeToken", function(done) {
        return wxt.loadAuthorzeToken("code", function(err, data) {
          if (err != null) {
            console.log(err);
          }
          console.dir(data);
          return done();
        });
      });
    });
  });

}).call(this);
